[gcp_service_account]
type = "service_account"
project_id = "biobest-pfe"
private_key_id = "02f5ed44f25ab0c6506feffd7355531dcec9eafc"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDbVZsluoPtwr9O
g/Ex80yaF/K7vKEpzT0IWSQhS2OI6ohE69ZunlNVCnSZxzNOqxruWNk04FzPf4vk
LJAq6dF7q7HUgWRD1d83IJH+9rWYUMXbEdbPgPKXnPcUj0AHtT043DmJZ/HQRukL
2Bxw0K7e+wNEtcuKaI2SI6O/aCoGXWcwoEEe6c+XgoKSK1sx8zN+5xdwkJXelvAu
pCpM5F61fii+HRFNkdctCKjcmKLXK4CkDzcvzMZxMOn2aeYsH372ewHcJlvaSec9
/FVKlLqmB9uj0r3oDW/priGoOYravJftQJWYOfSwbiuff7x0S/2IWTgn0VrM4Hs5
qV1dSxnNAgMBAAECggEASEM0EoIY5US8csnVtXdLTZmGR4QmNPeBnDaCSNXlvT5I
Fyz8QQW4vtPrBp8ysEB/Zveu2FTzPwnutQZZmUnf0rcGp9TZi9/y4t7AOxhdTAmQ
plSCSWtagckdPpDTr7ZurUUhT7wHV2+FaHmTJTgb5SseMI0Uuk0oF3XWhUF0VxPi
q8ar8meWcQ40Urbq5Mp3fFLN7iWsgBbsREv71O6BbU6oScRb0hoKprk/o6v0AKeR
ibXnu5aNKWE5deQYHQsyUxZLHNLwmyc0teTQ09U2+YEakkMA2iUeaNfKd5hnt3B+
OiejwliJ9vPRWVMvW6UHRCtEmAYRs+bxytuSMRQ5oQKBgQD0ha+kzaN4+yKiuHnH
id59K+aKrH8midsb1VjIN3XN7GHRBvanqK4d3MnaxglLy+4zLUXV1POSW+gAfX5v
+qA1TH3Rbg6D9yMA2C5ry0q325sPcEzJPQMZHrKVfm4RbQbU6WXTIcv4NtkDfLW8
1rFEeoVJDndGXmXcUzPqumhIUwKBgQDloT/QSFEkJJ5pXzQ2qN7593Hea6AOzN41
V5WN5L8EjVqwBASsuKTIMiG0nCkww8Zt+30CTCrD+KjFiOIwp6QY1i6IUalHW82l
1tjuCtYqdAQI9c4BON1363FP2JG4CAdD+sYzsJ3Vl60mdmSYhxKsbL4cBNUssJTr
5aLqeLJRXwKBgQDpfFn6oQ2OsScif8pxGZnkpi3OjuYe85XQXwkWrbaEeknw4ZhX
Ab+47iGlEGLCCKmcHofHpj8qqy2+ghZgcM3X9wFRIKklo6+916+D6KuhIkZPGKmJ
nowO5UdGu4/nQE+5pEbDUSTpN+nmAVe3nso20WNW6q+CCxhK3ro8tfO+k1wKBgQDX
D51XcdNkuVMPtxWMt74VeFVSDZRbKC5Y4Q11Vi48kjLENQ83wLq7sI/2umatgD3g
la+vrixDXCic0KWfEfLTPA1aqLiU13sT/dMvpkCMhBmfVq84X8yz2nNGZ7uaExLS
7RQiJyC7gZGuOyXd4Gtxx2qJjVElyL/A61IYrS+8mwKBgQCgeHac0QM7qIKVWjRp
PSlPKLnmGXt7l9SPu4I+QcyABXQ562lzPV5Zkor5nG7xx6VFNEALQLd15Qz+WNOW
NC43VOA8RCMF1u64oTN4E3tRRvasY/gV8ewjkKRtqurd6P2sCEzzvpAGohWeLtiE
S7RD6Gq4jU4/xh0qoYc/p23q1g==
-----END PRIVATE KEY-----"""
client_email = "biobest-robot@biobest-pfe.iam.gserviceaccount.com"
client_id = "109141969347277711181"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/biobest-robot%40biobest-pfe.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
